services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      POSTGRES_URI: "postgres://postgres:example@db:5432/postgres"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 3